<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CMSSeeder extends Seeder {
    public function run(): void {
        DB::table('c_m_s')->insert([
            [
                'id'          => 1,
                'section'     => 'questionnaires',
                'title'       => 'Answer a few quick questions to start building your profile and get started',
                'sub_title'   => null,
                'content'     => null,
                'description' => '<p>All information will be reviewed by our team to ensure compliance and maintain platform standards. Rest assured, your privacy and data security are our top priority.</p>',
                'image'       => null,
                'status'      => 'active',
                'created_at'  => '2025-06-10 06:13:55',
                'updated_at'  => '2025-06-10 06:13:55',
                'deleted_at'  => null,
            ],
            [
                'id'          => 2,
                'section'     => 'join_us',
                'title'       => 'Discover Beauty Services',
                'sub_title'   => null,
                'content'     => null,
                'description' => '<p>Step into a world of top-rated beauty professionals ready to cater to your unique needs. Whether you\'re looking for a new look or routine care, our platform connects you with the best beauty experts in your area. Explore a variety of services and easily book appointments that fit your schedule.</p>',
                'image'       => null,
                'status'      => 'active',
                'created_at'  => '2025-06-10 06:15:41',
                'updated_at'  => '2025-06-10 06:15:41',
                'deleted_at'  => null,
            ],
            [
                'id'          => 3,
                'section'     => 'user-type-container',
                'title'       => 'I\'m a Beauty Professional',
                'sub_title'   => null,
                'content'     => null,
                'description' => '<p>Join our platform to showcase your skills, connect with clients, and grow your beauty business. Benefit from secure payments and flexible scheduling.</p>',
                'image'       => 'frontend/uploads/home-user-type-1.png',
                'status'      => 'active',
                'created_at'  => '2025-06-10 06:18:42',
                'updated_at'  => '2025-06-10 06:19:10',
                'deleted_at'  => null,
            ],
            [
                'id'          => 4,
                'section'     => 'user-type-container',
                'title'       => 'I\'m Looking for a Beauty Service',
                'sub_title'   => null,
                'content'     => null,
                'description' => '<p>Find trusted beauty professionals near you, book an appointment for your next glam session, and experience top-tier service right at your convenience.</p>',
                'image'       => 'frontend/uploads/home-user-type-2.png',
                'status'      => 'active',
                'created_at'  => '2025-06-10 06:18:42',
                'updated_at'  => '2025-06-10 06:18:42',
                'deleted_at'  => null,
            ],
            [
                'id'          => 5,
                'section'     => 'user-dashboard',
                'title'       => null,
                'sub_title'   => null,
                'content'     => null,
                'description' => '<p>Start now to connect with trusted tax professionals, book appointments, and manage your documents—all in one place for a smooth tax preparation experience.</p>',
                'image'       => null,
                'status'      => 'active',
                'created_at'  => '2025-06-10 06:18:42',
                'updated_at'  => '2025-06-10 06:18:42',
                'deleted_at'  => null,
            ],
            [
                'id'          => 6,
                'section'     => 'home-page-banner',
                'title'       => null,
                'sub_title'   => null,
                'content'     => null,
                'description' => '<p>At Glamora we make finding top beauty professionals easy and stress-free. Explore and book trusted experts for all your beauty needs in one place !</p>',
                'image'       => null,
                'status'      => 'active',
                'created_at'  => '2025-06-10 06:18:42',
                'updated_at'  => '2025-06-10 06:18:42',
                'deleted_at'  => null,
            ],
            [
                'id'          => 7,
                'section'     => 'question-mark-text',
                'title'       => null,
                'sub_title'   => null,
                'content'     => null,
                'description' => '<p>Turn off the toggle to mark yourself as on leave or not accepting bookings—whether currently or for specific future dates. After switching it off, select your unavailable dates and save them. These will be reflected in your calendar automatically.</p>',
                'image'       => null,
                'status'      => 'active',
                'created_at'  => '2025-06-10 06:18:42',
                'updated_at'  => '2025-06-10 06:18:42',
                'deleted_at'  => null,
            ],
            [
                'id'          => 8,
                'section'     => 'profile-review-message',
                'title'       => 'Profile Submitted for Review!',
                'sub_title'   => null,
                'content'     => '<p>This process typically takes 1-2 business days. We appreciate your patience and look forward to having you on board!</p>',
                'description' => '<p>Thank you for providing your information! Our team is reviewing your details to ensure everything is in order. You will receive an <strong>email</strong> notification once your profile has been approved.</p>',
                'image'       => 'frontend/uploads/submit-review.png',
                'status'      => 'active',
                'created_at'  => '2025-06-10 06:18:42',
                'updated_at'  => '2025-06-10 06:18:42',
                'deleted_at'  => null,
            ],
            [
                'id'          => 9,
                'section'     => 'home-counter',
                'title'       => 'We’ve facilitated over 20,000 beauty appointments to date.',
                'sub_title'   => '20k+',
                'content'     => null,
                'description' => null,
                'image'       => null,
                'status'      => 'active',
                'created_at'  => '2025-06-10 06:18:42',
                'updated_at'  => '2025-06-10 06:18:42',
                'deleted_at'  => null,
            ],
            [
                'id'          => 10,
                'section'     => 'home-counter',
                'title'       => 'Our professionals have collectively earned over $5 million through our platform',
                'sub_title'   => '$5m+',
                'content'     => null,
                'description' => null,
                'image'       => null,
                'status'      => 'active',
                'created_at'  => '2025-06-10 06:18:42',
                'updated_at'  => '2025-06-10 06:18:42',
                'deleted_at'  => null,
            ],
            [
                'id'          => 11,
                'section'     => 'home-counter',
                'title'       => 'Over 1,500 certified beauty professionals available across the country.',
                'sub_title'   => '1,500+',
                'content'     => null,
                'description' => null,
                'image'       => null,
                'status'      => 'active',
                'created_at'  => '2025-06-10 06:18:42',
                'updated_at'  => '2025-06-10 06:18:42',
                'deleted_at'  => null,
            ],
            [
                'id'          => 12,
                'section'     => 'home-counter',
                'title'       => '98% of our clients are satisfied with the services they receive.',
                'sub_title'   => '98%',
                'content'     => null,
                'description' => null,
                'image'       => null,
                'status'      => 'active',
                'created_at'  => '2025-06-10 06:18:42',
                'updated_at'  => '2025-06-10 06:18:42',
                'deleted_at'  => null,
            ],
            [
                'id'          => 13,
                'section'     => 'home',
                'title'       => null,
                'sub_title'   => null,
                'content'     => null,
                'description' => null,
                'image'       => 'frontend/uploads/home-images/home-banner_1740888946.png',
                'status'      => 'active',
                'created_at'  => '2025-03-01 22:15:46',
                'updated_at'  => '2025-03-01 22:15:46',
                'deleted_at'  => null,
            ],
            [
                'id'          => 14,
                'section'     => 'home',
                'title'       => null,
                'sub_title'   => null,
                'content'     => null,
                'description' => null,
                'image'       => 'frontend/uploads/home-images/home-banner_1740888954.png',
                'status'      => 'active',
                'created_at'  => '2025-03-01 22:15:54',
                'updated_at'  => '2025-03-01 22:15:54',
                'deleted_at'  => null,
            ],
            [
                'id'          => 15,
                'section'     => 'home',
                'title'       => null,
                'sub_title'   => null,
                'content'     => null,
                'description' => null,
                'image'       => 'frontend/uploads/home-images/home-banner_1740888960.png',
                'status'      => 'active',
                'created_at'  => '2025-03-01 22:16:00',
                'updated_at'  => '2025-03-01 22:16:00',
                'deleted_at'  => null,
            ],
            [
                'id'          => 16,
                'section'     => 'auth',
                'title'       => null,
                'sub_title'   => null,
                'content'     => null,
                'description' => null,
                'image'       => 'frontend/uploads/auth-images/auth-banner_1740889150.png',
                'status'      => 'active',
                'created_at'  => '2025-03-01 22:19:10',
                'updated_at'  => '2025-03-01 22:19:10',
                'deleted_at'  => null,
            ],
            [
                'id'          => 17,
                'section'     => 'testimonial',
                'title'       => null,
                'sub_title'   => null,
                'content'     => null,
                'description' => null,
                'image'       => 'frontend/uploads/home-testimonial-img.png',
                'status'      => 'active',
                'created_at'  => '2025-03-01 22:19:10',
                'updated_at'  => '2025-03-01 22:19:10',
                'deleted_at'  => null,
            ],
        ]);
    }
}
