<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserToolSeeder extends Seeder {
    public function run(): void {
        DB::table('user_tools')->insert([
            [
                'id'         => 1,
                'user_id'    => 3,
                'tool_name'  => 'MAC',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 2,
                'user_id'    => 3,
                'tool_name'  => 'Charlotte Tilbury',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 3,
                'user_id'    => 3,
                'tool_name'  => 'Estée Lauder',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 4,
                'user_id'    => 3,
                'tool_name'  => 'Bobbi Brown',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 5,
                'user_id'    => 3,
                'tool_name'  => 'Huda Beauty',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 6,
                'user_id'    => 3,
                'tool_name'  => 'Huda Beauty',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 7,
                'user_id'    => 3,
                'tool_name'  => 'Huda Beauty',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 8,
                'user_id'    => 3,
                'tool_name'  => 'Huda Beauty',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 9,
                'user_id'    => 5,
                'tool_name'  => 'MAC',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 10,
                'user_id'    => 5,
                'tool_name'  => 'Charlotte Tilbury',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 11,
                'user_id'    => 5,
                'tool_name'  => 'Estée Lauder',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 12,
                'user_id'    => 5,
                'tool_name'  => 'Bobbi Brown',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 13,
                'user_id'    => 5,
                'tool_name'  => 'Huda Beauty',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 14,
                'user_id'    => 5,
                'tool_name'  => 'Huda Beauty',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 15,
                'user_id'    => 5,
                'tool_name'  => 'Huda Beauty',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 16,
                'user_id'    => 5,
                'tool_name'  => 'Huda Beauty',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 17,
                'user_id'    => 6,
                'tool_name'  => 'MAC',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 18,
                'user_id'    => 6,
                'tool_name'  => 'Charlotte Tilbury',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 19,
                'user_id'    => 6,
                'tool_name'  => 'Estée Lauder',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 20,
                'user_id'    => 6,
                'tool_name'  => 'Bobbi Brown',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 21,
                'user_id'    => 6,
                'tool_name'  => 'Huda Beauty',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 22,
                'user_id'    => 6,
                'tool_name'  => 'Huda Beauty',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 23,
                'user_id'    => 6,
                'tool_name'  => 'Huda Beauty',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 24,
                'user_id'    => 6,
                'tool_name'  => 'Huda Beauty',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 25,
                'user_id'    => 7,
                'tool_name'  => 'MAC',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 26,
                'user_id'    => 7,
                'tool_name'  => 'Charlotte Tilbury',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 27,
                'user_id'    => 7,
                'tool_name'  => 'Estée Lauder',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 28,
                'user_id'    => 7,
                'tool_name'  => 'Bobbi Brown',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 29,
                'user_id'    => 7,
                'tool_name'  => 'Huda Beauty',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 30,
                'user_id'    => 7,
                'tool_name'  => 'Huda Beauty',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 31,
                'user_id'    => 7,
                'tool_name'  => 'Huda Beauty',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 32,
                'user_id'    => 7,
                'tool_name'  => 'Huda Beauty',
                'status'     => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
