<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder {
    public function run(): void {
        DB::table('users')->insert([
            [
                'id'                       => 1,
                'first_name'               => 'admin',
                'last_name'                => 'user',
                'email'                    => 'admin@admin.com',
                'phone_number'             => '1234567890',
                'address'                  => 'Australia',
                'email_verified_at'        => '2025-01-31 23:29:49',
                'phone_number_verified_at' => '2025-01-31 23:29:49',
                'password'                 => Hash::make('12345678'),
                'role'                     => 'admin',
                'status'                   => 'active',
                'remember_token'           => null,
                'created_at'               => '2025-01-31 23:29:49',
                'updated_at'               => '2025-01-31 23:29:49',
                'deleted_at'               => null,
            ],
            [
                'id'                       => 2,
                'first_name'               => 'client',
                'last_name'                => 'user',
                'email'                    => 'client@client.com',
                'phone_number'             => '0123456789',
                'address'                  => 'Bronx, New York, United States',
                'email_verified_at'        => '2025-01-31 23:29:49',
                'phone_number_verified_at' => '2025-01-31 23:29:49',
                'password'                 => Hash::make('12345678'),
                'role'                     => 'client',
                'status'                   => 'active',
                'remember_token'           => null,
                'created_at'               => '2025-01-31 23:29:49',
                'updated_at'               => '2025-01-31 23:29:49',
                'deleted_at'               => null,
            ],
            [
                'id'                       => 3,
                'first_name'               => 'beauty',
                'last_name'                => 'expert',
                'email'                    => 'beauty-expert@beauty-expert.com',
                'phone_number'             => '1234567891',
                'address'                  => 'Sydney, New South Wales, Australia',
                'email_verified_at'        => '2025-01-31 23:29:49',
                'phone_number_verified_at' => '2025-01-31 23:29:49',
                'password'                 => Hash::make('12345678'),
                'role'                     => 'beauty_expert',
                'status'                   => 'active',
                'remember_token'           => null,
                'created_at'               => '2025-01-31 23:29:49',
                'updated_at'               => '2025-01-31 23:29:49',
                'deleted_at'               => null,
            ],
            [
                'id'                       => 4,
                'first_name'               => 'glamora',
                'last_name'                => 'user',
                'email'                    => 'user@user.com',
                'phone_number'             => '1234567892',
                'address'                  => 'Melbourne, Victoria, Australia',
                'email_verified_at'        => '2025-01-31 23:30:36',
                'phone_number_verified_at' => '2025-01-31 23:30:36',
                'password'                 => Hash::make('12345678'),
                'role'                     => 'client',
                'status'                   => 'active',
                'remember_token'           => null,
                'created_at'               => '2025-01-31 23:30:36',
                'updated_at'               => '2025-01-31 23:30:36',
                'deleted_at'               => null,
            ],
            [
                'id'                       => 5,
                'first_name'               => 'test',
                'last_name'                => 'user',
                'email'                    => 'test@test.com',
                'phone_number'             => '1234567893',
                'address'                  => 'Perth, Western Australia, Australia',
                'email_verified_at'        => '2025-01-31 23:31:23',
                'phone_number_verified_at' => '2025-01-31 23:31:23',
                'password'                 => Hash::make('12345678'),
                'role'                     => 'beauty_expert',
                'status'                   => 'active',
                'remember_token'           => null,
                'created_at'               => '2025-01-31 23:31:23',
                'updated_at'               => '2025-01-31 23:40:35',
                'deleted_at'               => null,
            ],
            [
                'id'                       => 6,
                'first_name'               => 'Hafizur Rahman',
                'last_name'                => 'Shadhin',
                'email'                    => 'shadhin666@gmail.com',
                'phone_number'             => '+8801719922812',
                'address'                  => 'Dhaka, Bangladesh',
                'email_verified_at'        => '2025-01-31 23:37:30',
                'phone_number_verified_at' => '2025-01-31 23:37:30',
                'password'                 => Hash::make('12345678'),
                'role'                     => 'beauty_expert',
                'status'                   => 'active',
                'remember_token'           => null,
                'created_at'               => '2025-01-31 23:37:30',
                'updated_at'               => '2025-01-31 23:40:33',
                'deleted_at'               => null,
            ],
            [
                'id'                       => 7,
                'first_name'               => 'Ezekiel',
                'last_name'                => 'Odonnell',
                'email'                    => 'ezekiel@gmail.com',
                'phone_number'             => '1234567894',
                'address'                  => 'New South Wales, Australia',
                'email_verified_at'        => '2025-02-04 04:42:36',
                'phone_number_verified_at' => '2025-02-04 04:42:36',
                'password'                 => Hash::make('12345678'),
                'role'                     => 'beauty_expert',
                'status'                   => 'active',
                'remember_token'           => null,
                'created_at'               => '2025-02-04 04:42:36',
                'updated_at'               => '2025-02-04 04:44:35',
                'deleted_at'               => null,
            ],
        ]);
    }
}
