<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserServiceSeeder extends Seeder {
    public function run(): void {
        DB::table('user_services')->insert([
            [
                'id'            => 1,
                'user_id'       => 3,
                'service_id'    => 1,
                'selected'      => 1,
                'offered_price' => 10.00,
                'total_price'   => 12.00,
                'image'         => 'frontend/service-image-2.jpg',
                'status'        => 'active',
                'created_at'    => '2025-01-22 18:41:42',
                'updated_at'    => '2025-01-22 18:43:00',
                'deleted_at'    => null,
            ],
            [
                'id'            => 2,
                'user_id'       => 3,
                'service_id'    => 2,
                'selected'      => 1,
                'offered_price' => 20.00,
                'total_price'   => 24.00,
                'image'         => 'frontend/service-image-2.jpg',
                'status'        => 'active',
                'created_at'    => '2025-01-22 18:41:42',
                'updated_at'    => '2025-01-22 18:43:01',
                'deleted_at'    => null,
            ],
            [
                'id'            => 3,
                'user_id'       => 3,
                'service_id'    => 3,
                'selected'      => 1,
                'offered_price' => 30.00,
                'total_price'   => 36.00,
                'image'         => 'frontend/service-image-2.jpg',
                'status'        => 'active',
                'created_at'    => '2025-01-22 18:41:42',
                'updated_at'    => '2025-01-22 18:43:02',
                'deleted_at'    => null,
            ],
            [
                'id'            => 4,
                'user_id'       => 3,
                'service_id'    => 4,
                'selected'      => 1,
                'offered_price' => 40.00,
                'total_price'   => 48.00,
                'image'         => 'frontend/service-image-2.jpg',
                'status'        => 'active',
                'created_at'    => '2025-01-22 18:41:42',
                'updated_at'    => '2025-01-22 18:43:03',
                'deleted_at'    => null,
            ],
            [
                'id'            => 5,
                'user_id'       => 3,
                'service_id'    => 5,
                'selected'      => 1,
                'offered_price' => 50.00,
                'total_price'   => 60.00,
                'image'         => 'frontend/service-image-2.jpg',
                'status'        => 'active',
                'created_at'    => '2025-01-22 18:41:42',
                'updated_at'    => '2025-01-22 18:43:04',
                'deleted_at'    => null,
            ],
            [
                'id'            => 6,
                'user_id'       => 3,
                'service_id'    => 6,
                'selected'      => 1,
                'offered_price' => 60.00,
                'total_price'   => 72.00,
                'image'         => 'frontend/service-image-2.jpg',
                'status'        => 'active',
                'created_at'    => '2025-01-22 18:41:42',
                'updated_at'    => '2025-01-22 18:43:05',
                'deleted_at'    => null,
            ],
            [
                'id'            => 7,
                'user_id'       => 3,
                'service_id'    => 7,
                'selected'      => 1,
                'offered_price' => 70.00,
                'total_price'   => 84.00,
                'image'         => 'frontend/service-image-2.jpg',
                'status'        => 'active',
                'created_at'    => '2025-01-22 18:41:42',
                'updated_at'    => '2025-01-22 18:43:06',
                'deleted_at'    => null,
            ],
            [
                'id'            => 8,
                'user_id'       => 5,
                'service_id'    => 1,
                'selected'      => 1,
                'offered_price' => 100.00,
                'total_price'   => 120.00,
                'image'         => 'frontend/service-image.jpg',
                'status'        => 'active',
                'created_at'    => '2025-01-31 23:36:11',
                'updated_at'    => '2025-01-31 23:42:11',
                'deleted_at'    => null,
            ],
            [
                'id'            => 9,
                'user_id'       => 5,
                'service_id'    => 2,
                'selected'      => 1,
                'offered_price' => 200.00,
                'total_price'   => 240.00,
                'image'         => 'frontend/service-image.jpg',
                'status'        => 'active',
                'created_at'    => '2025-01-31 23:36:11',
                'updated_at'    => '2025-01-31 23:42:10',
                'deleted_at'    => null,
            ],
            [
                'id'            => 10,
                'user_id'       => 5,
                'service_id'    => 3,
                'selected'      => 1,
                'offered_price' => 300.00,
                'total_price'   => 360.00,
                'image'         => 'frontend/service-image.jpg',
                'status'        => 'active',
                'created_at'    => '2025-01-31 23:36:11',
                'updated_at'    => '2025-01-31 23:42:13',
                'deleted_at'    => null,
            ],
            [
                'id'            => 11,
                'user_id'       => 5,
                'service_id'    => 4,
                'selected'      => 1,
                'offered_price' => 400.00,
                'total_price'   => 480.00,
                'image'         => 'frontend/service-image.jpg',
                'status'        => 'active',
                'created_at'    => '2025-01-31 23:36:11',
                'updated_at'    => '2025-01-31 23:42:22',
                'deleted_at'    => null,
            ],
            [
                'id'            => 12,
                'user_id'       => 5,
                'service_id'    => 5,
                'selected'      => 1,
                'offered_price' => 500.00,
                'total_price'   => 600.00,
                'image'         => 'frontend/service-image.jpg',
                'status'        => 'active',
                'created_at'    => '2025-01-31 23:36:11',
                'updated_at'    => '2025-01-31 23:42:23',
                'deleted_at'    => null,
            ],
            [
                'id'            => 13,
                'user_id'       => 5,
                'service_id'    => 6,
                'selected'      => 1,
                'offered_price' => 600.00,
                'total_price'   => 720.00,
                'image'         => 'frontend/service-image.jpg',
                'status'        => 'active',
                'created_at'    => '2025-01-31 23:36:11',
                'updated_at'    => '2025-01-31 23:42:24',
                'deleted_at'    => null,
            ],
            [
                'id'            => 14,
                'user_id'       => 5,
                'service_id'    => 7,
                'selected'      => 1,
                'offered_price' => 700.00,
                'total_price'   => 840.00,
                'image'         => 'frontend/service-image.jpg',
                'status'        => 'active',
                'created_at'    => '2025-01-31 23:36:11',
                'updated_at'    => '2025-01-31 23:42:25',
                'deleted_at'    => null,
            ],
            [
                'id'            => 15,
                'user_id'       => 6,
                'service_id'    => 1,
                'selected'      => 1,
                'offered_price' => 123.00,
                'total_price'   => 147.60,
                'image'         => 'frontend/home-user-type-2.png',
                'status'        => 'active',
                'created_at'    => '2025-01-31 23:39:59',
                'updated_at'    => '2025-01-31 23:41:57',
                'deleted_at'    => null,
            ],
            [
                'id'            => 16,
                'user_id'       => 6,
                'service_id'    => 2,
                'selected'      => 1,
                'offered_price' => 456.00,
                'total_price'   => 547.20,
                'image'         => 'frontend/home-user-type-2.png',
                'status'        => 'active',
                'created_at'    => '2025-01-31 23:39:59',
                'updated_at'    => '2025-01-31 23:42:02',
                'deleted_at'    => null,
            ],
            [
                'id'            => 17,
                'user_id'       => 6,
                'service_id'    => 3,
                'selected'      => 1,
                'offered_price' => 789.00,
                'total_price'   => 946.80,
                'image'         => 'frontend/home-user-type-2.png',
                'status'        => 'active',
                'created_at'    => '2025-01-31 23:39:59',
                'updated_at'    => '2025-01-31 23:42:03',
                'deleted_at'    => null,
            ],
            [
                'id'            => 18,
                'user_id'       => 6,
                'service_id'    => 4,
                'selected'      => 1,
                'offered_price' => 147.00,
                'total_price'   => 176.40,
                'image'         => 'frontend/home-user-type-2.png',
                'status'        => 'active',
                'created_at'    => '2025-01-31 23:39:59',
                'updated_at'    => '2025-01-31 23:42:04',
                'deleted_at'    => null,
            ],
            [
                'id'            => 19,
                'user_id'       => 6,
                'service_id'    => 5,
                'selected'      => 1,
                'offered_price' => 258.00,
                'total_price'   => 309.60,
                'image'         => 'frontend/home-user-type-2.png',
                'status'        => 'active',
                'created_at'    => '2025-01-31 23:39:59',
                'updated_at'    => '2025-01-31 23:42:05',
                'deleted_at'    => null,
            ],
            [
                'id'            => 20,
                'user_id'       => 6,
                'service_id'    => 6,
                'selected'      => 1,
                'offered_price' => 369.00,
                'total_price'   => 442.80,
                'image'         => 'frontend/home-user-type-2.png',
                'status'        => 'active',
                'created_at'    => '2025-01-31 23:39:59',
                'updated_at'    => '2025-01-31 23:42:07',
                'deleted_at'    => null,
            ],
            [
                'id'            => 21,
                'user_id'       => 6,
                'service_id'    => 7,
                'selected'      => 1,
                'offered_price' => 159.00,
                'total_price'   => 190.80,
                'image'         => 'frontend/home-user-type-2.png',
                'status'        => 'active',
                'created_at'    => '2025-01-31 23:39:59',
                'updated_at'    => '2025-01-31 23:42:08',
                'deleted_at'    => null,
            ],
        ]);
    }
}
